
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.UI
{
public partial class TbUIFormConfig
{
    private readonly System.Collections.Generic.Dictionary<int, UI.UIFormConfig> _dataMap;
    private readonly System.Collections.Generic.List<UI.UIFormConfig> _dataList;
    
    public TbUIFormConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UI.UIFormConfig>();
        _dataList = new System.Collections.Generic.List<UI.UIFormConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UI.UIFormConfig _v;
            _v = global::GameConfig.UI.UIFormConfig.DeserializeUIFormConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UI.UIFormConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.UIFormConfig> DataList => _dataList;

    public UI.UIFormConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.UIFormConfig Get(int key) => _dataMap[key];
    public UI.UIFormConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

