
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Entity
{
public sealed partial class EntityGroupConfig : Luban.BeanBase
{
    public EntityGroupConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ReleaseInterval = _buf.ReadFloat();
        Capacity = _buf.ReadInt();
        ExpireTime = _buf.ReadFloat();
        Priority = _buf.ReadInt();
    }

    public static EntityGroupConfig DeserializeEntityGroupConfig(ByteBuf _buf)
    {
        return new Entity.EntityGroupConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体组名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 释放时间间隔
    /// </summary>
    public readonly float ReleaseInterval;
    /// <summary>
    /// 对象池容量
    /// </summary>
    public readonly int Capacity;
    /// <summary>
    /// 对象池过期时间（秒）
    /// </summary>
    public readonly float ExpireTime;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = -1687508621;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "ReleaseInterval:" + ReleaseInterval + ","
        + "Capacity:" + Capacity + ","
        + "ExpireTime:" + ExpireTime + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}

}

