
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Entity
{
public partial class TbEntityGroupConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Entity.EntityGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<Entity.EntityGroupConfig> _dataList;
    
    public TbEntityGroupConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Entity.EntityGroupConfig>();
        _dataList = new System.Collections.Generic.List<Entity.EntityGroupConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Entity.EntityGroupConfig _v;
            _v = global::GameConfig.Entity.EntityGroupConfig.DeserializeEntityGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Entity.EntityGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Entity.EntityGroupConfig> DataList => _dataList;

    public Entity.EntityGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Entity.EntityGroupConfig Get(int key) => _dataMap[key];
    public Entity.EntityGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

