
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Sound
{
public sealed partial class SoundConfig : Luban.BeanBase
{
    public SoundConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        AgentCounts = _buf.ReadInt();
        AvoidBeingReplacedBySamePriority = _buf.ReadBool();
    }

    public static SoundConfig DeserializeSoundConfig(ByteBuf _buf)
    {
        return new Sound.SoundConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体组名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 可使用声音代理数量
    /// </summary>
    public readonly int AgentCounts;
    /// <summary>
    /// 避免被同等优先级替换
    /// </summary>
    public readonly bool AvoidBeingReplacedBySamePriority;
   
    public const int __ID__ = 1536834194;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "AgentCounts:" + AgentCounts + ","
        + "AvoidBeingReplacedBySamePriority:" + AvoidBeingReplacedBySamePriority + ","
        + "}";
    }
}

}

