#if TOOLS
using GameFramework;
using Godot;
using GodotGameFramework.Resource;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

[Tool]
public partial class ResourcesCollectionEditor : EditorPlugin
{
	const string MENU_ITEM_NAME = "CollectionRes";
	const string MAINFOLDER = "res://TheGame/";
	const string SCRIPTFOLDER = "res://TheGame/GameScripts/";
	const string OUTPUT_FILE = "res://TheGame/GameScripts/GameProto/ResourcesCollectionConstant.cs";
	public string GameVersion = "1.0.0";
	public int InternalResourceVersion = 1;

	public override void _EnterTree()
	{
		AddToolMenuItem(MENU_ITEM_NAME, new Callable(this, nameof(OnMenuPressed)));
		GD.Print("[ResourcesCollection] Plugin loaded.");
	}

	public override void _ExitTree()
	{
		RemoveToolMenuItem(MENU_ITEM_NAME);
		GD.Print("[ResourcesCollection] Plugin unloaded.");
	}

	private void OnMenuPressed()
	{
		string versionListPath = Utility.Path.GetRegularPath(
			System.IO.Path.Combine(GameFolderConstant.ReadOnlyPath, GameFolderConstant.GameFrameworkVersionData));
		GDFResourceBuilder.BuildVersionList(GameFolderConstant.ReadOnlyPath, versionListPath,
			GameVersion, InternalResourceVersion);
		CollectionRes();
	}

	/// <summary>
	/// 收集 TheGame 文件夹下所有非脚本资源文件路径，生成到 ResourcesCollectionConstant.cs。
	/// 使用 DirAccess 遍历以保证路径分隔符统一为 '/'。
	/// 发现同名文件（不同路径）时会报错并中止生成。
	/// </summary>
	private void CollectionRes()
	{
		// 使用 DirAccess 遍历 Godot 资源目录，保证路径统一为 "res://" 格式
		var allFiles = new List<string>();
		var dir = DirAccess.Open(MAINFOLDER);
		if (dir == null)
		{
			GD.PrintErr($"[ResourcesCollection] Can not open directory: {MAINFOLDER}");
			return;
		}

		CollectFilesRecursive(dir, MAINFOLDER, allFiles);

		// 过滤规则：
		//   1. 排除 .cs 脚本文件
		//   2. 排除 GameScripts/ 目录下的所有文件（包含 .cs 和可能的元数据）
		//   3. 排除 .import 文件（Godot 资源导入元数据，非实际资源）
		var resourceFiles = allFiles
			.Where(f => !f.EndsWith(".cs"))
			.Where(f => !f.StartsWith(SCRIPTFOLDER))
			.Where(f => !f.EndsWith(".import"))
			.Where(f => !f.EndsWith(".uid"))
			.OrderBy(f => f)
			.ToList();

		if (resourceFiles.Count == 0)
		{
			GD.Print("[ResourcesCollection] No resource files found.");
			return;
		}

		// 检查同名文件（不同路径）：如果有相同文件名（不含扩展名）直接报错
		var duplicateNames = resourceFiles
			.GroupBy(f => Path.GetFileNameWithoutExtension(f))
			.Where(g => g.Count() > 1)
			.ToList();

		if (duplicateNames.Count > 0)
		{
			GD.PrintErr("[ResourcesCollection] 有相同文件，请修改");
			foreach (var group in duplicateNames)
			{
				GD.PrintErr($"  Duplicate name: \"{group.Key}\"");
				foreach (var f in group)
				{
					GD.PrintErr($"    - {f}");
				}
			}
			return;
		}

		var lines = new List<string>();

		foreach (var file in resourceFiles)
		{
			string constName = Path.GetFileNameWithoutExtension(file);

			// 常量名不能以数字开头
			if (constName.Length > 0 && char.IsDigit(constName[0]))
				constName = $"_{constName}";

			lines.Add($"\t\tpublic const string {constName} = \"{file}\";");
		}

		// 生成完整 C# 文件内容
		string fileContent = $"//------------------------------------------------------------\n" +
			$"// Resources Collection Constant\n" +
			$"// Auto-generated by ResourcesCollection plugin.\n" +
			$"// Do not modify manually.\n" +
			$"// Generation time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}\n" +
			$"//------------------------------------------------------------\n" +
			$"\n" +
			$"namespace TheGame\n" +
			$"{{\n" +
			$"\tpublic static class ResourcesCollectionConstant\n" +
			$"\t{{\n" +
			string.Join("\n", lines) + "\n" +
			$"\t}}\n" +
			$"}}\n";

		string outputPath = ProjectSettings.GlobalizePath(OUTPUT_FILE);
		File.WriteAllText(outputPath, fileContent);

		GD.Print($"[ResourcesCollection] Collection complete. {resourceFiles.Count} resources saved to: {OUTPUT_FILE}");

		// 刷新文件系统让编辑器立即看到新文件
		EditorInterface.Singleton.GetResourceFilesystem().Scan();
	}

	private static void CollectFilesRecursive(DirAccess dir, string currentPath, List<string> results)
	{
		dir.ListDirBegin();

		while (true)
		{
			string fileName = dir.GetNext();
			if (string.IsNullOrEmpty(fileName))
				break;

			if (fileName == "." || fileName == "..")
				continue;

			string fullPath = currentPath.TrimEnd('/') + "/" + fileName;

			if (dir.CurrentIsDir())
			{
				var subDir = DirAccess.Open(fullPath);
				if (subDir != null)
				{
					CollectFilesRecursive(subDir, fullPath, results);
				}
			}
			else
			{
				results.Add(fullPath);
			}
		}

		dir.ListDirEnd();
	}
}
#endif