
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Character
{
public sealed partial class CharacterConfig : Luban.BeanBase
{
    public CharacterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        Speed = _buf.ReadInt();
    }

    public static CharacterConfig DeserializeCharacterConfig(ByteBuf _buf)
    {
        return new Character.CharacterConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体名称
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int Speed;
   
    public const int __ID__ = -1306483002;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "Speed:" + Speed + ","
        + "}";
    }
}

}

