
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Character
{
public partial class TbCharacterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Character.CharacterConfig> _dataMap;
    private readonly System.Collections.Generic.List<Character.CharacterConfig> _dataList;
    
    public TbCharacterConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.CharacterConfig>();
        _dataList = new System.Collections.Generic.List<Character.CharacterConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Character.CharacterConfig _v;
            _v = global::GameConfig.Character.CharacterConfig.DeserializeCharacterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.CharacterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.CharacterConfig> DataList => _dataList;

    public Character.CharacterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character.CharacterConfig Get(int key) => _dataMap[key];
    public Character.CharacterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

