//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by ResourcesCollection plugin.
// Do not modify manually.
// Generation time: 2026-06-26 17:17:11
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
	{
		public const string Audios_AudioBus = "res://TheGame/Audios/AudioBus.tres";
		public const string Music_Menu = "res://TheGame/Audios/Music/Menu.wav";
		public const string SFX_AtkUp = "res://TheGame/Audios/SFX/AtkUp.wav";
		public const string SFX_Dead = "res://TheGame/Audios/SFX/Dead.MP3";
		public const string SFX_Fight = "res://TheGame/Audios/SFX/Fight.wav";
		public const string SFX_Heal = "res://TheGame/Audios/SFX/Heal.wav";
		public const string SFX_PaoDan = "res://TheGame/Audios/SFX/PaoDan.mp3";
		public const string SFX_Shoot = "res://TheGame/Audios/SFX/Shoot.mp3";
		public const string GameConfigs_character_tbcharacterconfig = "res://TheGame/DataTables/GameConfigs/character_tbcharacterconfig.bytes";
		public const string GameConfigs_entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string GameConfigs_entity_tbentitygroupconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentitygroupconfig.bytes";
		public const string GameConfigs_sound_tbsoundconfig = "res://TheGame/DataTables/GameConfigs/sound_tbsoundconfig.bytes";
		public const string GameConfigs_tbuiformconfig = "res://TheGame/DataTables/GameConfigs/tbuiformconfig.bytes";
		public const string GameConfigs_tbuigroupconfig = "res://TheGame/DataTables/GameConfigs/tbuigroupconfig.bytes";
		public const string Localizations_ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string Localizations_English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Entitys_Cat = "res://TheGame/Entitys/Cat.tscn";
		public const string Fonts_simhei = "res://TheGame/Fonts/simhei.ttf";
		public const string Scenes_Map = "res://TheGame/Scenes/Map.tscn";
		public const string Sprites_btn = "res://TheGame/Sprites/btn.png";
		public const string Sprites_fuhao = "res://TheGame/Sprites/fuhao.png";
		public const string Sprites_map1 = "res://TheGame/Sprites/map1.png";
		public const string Sprites_paper = "res://TheGame/Sprites/paper.png";
		public const string Sprites_Y1 = "res://TheGame/Sprites/Y1.png";
		public const string Themes_bullt = "res://TheGame/Themes/bullt.tres";
		public const string UIs_GameOver = "res://TheGame/UIs/GameOver.tscn";
		public const string UIs_MainForm = "res://TheGame/UIs/MainForm.tscn";
		public const string UIs_MenuForm = "res://TheGame/UIs/MenuForm.tscn";
		public const string UIs_PauseMenu = "res://TheGame/UIs/PauseMenu.tscn";
		public const string UIs_RedBlock = "res://TheGame/UIs/RedBlock.tscn";
		public const string UIs_ScoreBlock = "res://TheGame/UIs/ScoreBlock.tscn";
		public const string UIs_ScorePopup = "res://TheGame/UIs/ScorePopup.tscn";
		public const string UIs_TestEntity = "res://TheGame/UIs/TestEntity.tscn";
		public const string UIs_TestOverlay = "res://TheGame/UIs/TestOverlay.tscn";
	}
}
