//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by ResourcesCollection plugin.
// Do not modify manually.
// Generation time: 2026-06-25 01:21:20
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
	{
		public const string 背景音乐 = "res://TheGame/Audios/背景音乐.mp3";
		public const string 点击方块音效 = "res://TheGame/Audios/点击方块音效.mp3";
		public const string character_tbcharacterconfig = "res://TheGame/DataTables/GameConfigs/character_tbcharacterconfig.bytes";
		public const string entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string entity_tbentitygroupconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentitygroupconfig.bytes";
		public const string sound_tbsoundconfig = "res://TheGame/DataTables/GameConfigs/sound_tbsoundconfig.bytes";
		public const string tbuiformconfig = "res://TheGame/DataTables/GameConfigs/tbuiformconfig.bytes";
		public const string tbuigroupconfig = "res://TheGame/DataTables/GameConfigs/tbuigroupconfig.bytes";
		public const string ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Cat = "res://TheGame/Entitys/Cat.tscn";
		public const string simhei = "res://TheGame/Fonts/simhei.ttf";
		public const string Map = "res://TheGame/Scenes/Map.tscn";
		public const string btn = "res://TheGame/Sprites/btn.png";
		public const string fuhao = "res://TheGame/Sprites/fuhao.png";
		public const string map1 = "res://TheGame/Sprites/map1.png";
		public const string paper = "res://TheGame/Sprites/paper.png";
		public const string Y1 = "res://TheGame/Sprites/Y1.png";
		public const string bullt = "res://TheGame/Themes/bullt.tres";
		public const string GameOver = "res://TheGame/UIs/GameOver.tscn";
		public const string MainForm = "res://TheGame/UIs/MainForm.tscn";
		public const string MenuForm = "res://TheGame/UIs/MenuForm.tscn";
		public const string PauseMenu = "res://TheGame/UIs/PauseMenu.tscn";
		public const string RedBlock = "res://TheGame/UIs/RedBlock.tscn";
		public const string ScoreBlock = "res://TheGame/UIs/ScoreBlock.tscn";
		public const string ScorePopup = "res://TheGame/UIs/ScorePopup.tscn";
		public const string TestEntity = "res://TheGame/UIs/TestEntity.tscn";
		public const string TestOverlay = "res://TheGame/UIs/TestOverlay.tscn";
	}
}
