//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by ResourcesCollection plugin.
// Do not modify manually.
// Generation time: 2026-06-14 23:05:19
//------------------------------------------------------------

namespace TheGame
{
	public static class ResourcesCollectionConstant
	{
		public const string 背景音乐 = "res://TheGame/Audio/背景音乐.mp3";
		public const string 点击方块音效 = "res://TheGame/Audio/点击方块音效.mp3";
		public const string item_tbitem = "res://TheGame/DataTables/item_tbitem.bytes";
		public const string Gameframework = "res://TheGame/Scenes/Gameframework.tscn";
		public const string GameHUD = "res://TheGame/UI/GameHUD.tscn";
		public const string GameOver = "res://TheGame/UI/GameOver.tscn";
		public const string MainMenu = "res://TheGame/UI/MainMenu.tscn";
		public const string PauseMenu = "res://TheGame/UI/PauseMenu.tscn";
		public const string RedBlock = "res://TheGame/UI/RedBlock.tscn";
		public const string ScoreBlock = "res://TheGame/UI/ScoreBlock.tscn";
		public const string ScorePopup = "res://TheGame/UI/ScorePopup.tscn";
		public const string TestEntity = "res://TheGame/UI/TestEntity.tscn";
		public const string TestOverlay = "res://TheGame/UI/TestOverlay.tscn";
	}
}
