
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LocalizationConfig : Luban.BeanBase
{
    public LocalizationConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        Value = _buf.ReadString();
    }

    public static LocalizationConfig DeserializeLocalizationConfig(ByteBuf _buf)
    {
        return new LocalizationConfig(_buf);
    }

    /// <summary>
    /// index
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 值
    /// </summary>
    public readonly string Value;
   
    public const int __ID__ = -1901143205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}

