
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MonsterSpawnWaves : Luban.BeanBase
{
    public MonsterSpawnWaves(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static MonsterSpawnWaves DeserializeMonsterSpawnWaves(ByteBuf _buf)
    {
        return new MonsterSpawnWaves(_buf);
    }

    public readonly int Id;
    public readonly int Num;
   
    public const int __ID__ = 1414641977;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Num:" + Num + ","
        + "}";
    }
}
}

