
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public TbUIFormConfig TbUIFormConfig {get; }
    public TbUIGroupConfig TbUIGroupConfig {get; }
    public Entity.TbEntityGroupConfig TbEntityGroupConfig {get; }
    public Entity.TbEntityConfig TbEntityConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbUIFormConfig = new TbUIFormConfig(loader("tbuiformconfig"));
        TbUIGroupConfig = new TbUIGroupConfig(loader("tbuigroupconfig"));
        TbEntityGroupConfig = new Entity.TbEntityGroupConfig(loader("entity_tbentitygroupconfig"));
        TbEntityConfig = new Entity.TbEntityConfig(loader("entity_tbentityconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbUIFormConfig.ResolveRef(this);
        TbUIGroupConfig.ResolveRef(this);
        TbEntityGroupConfig.ResolveRef(this);
        TbEntityConfig.ResolveRef(this);
    }
}

}
