
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TbUIFormConfig TbUIFormConfig {get; }
    public TbUIGroupConfig TbUIGroupConfig {get; }
    public Entity.TbEntityGroupConfig TbEntityGroupConfig {get; }
    public Entity.TbEntityConfig TbEntityConfig {get; }
    public Sound.TbSoundConfig TbSoundConfig {get; }
    public Character.TbCharacterConfig TbCharacterConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbUIFormConfig = new TbUIFormConfig(loader("tbuiformconfig"));
        TbUIGroupConfig = new TbUIGroupConfig(loader("tbuigroupconfig"));
        TbEntityGroupConfig = new Entity.TbEntityGroupConfig(loader("entity_tbentitygroupconfig"));
        TbEntityConfig = new Entity.TbEntityConfig(loader("entity_tbentityconfig"));
        TbSoundConfig = new Sound.TbSoundConfig(loader("sound_tbsoundconfig"));
        TbCharacterConfig = new Character.TbCharacterConfig(loader("character_tbcharacterconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbUIFormConfig.ResolveRef(this);
        TbUIGroupConfig.ResolveRef(this);
        TbEntityGroupConfig.ResolveRef(this);
        TbEntityConfig.ResolveRef(this);
        TbSoundConfig.ResolveRef(this);
        TbCharacterConfig.ResolveRef(this);
    }
}

}
