
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbUIGroupConfig
{
    private readonly System.Collections.Generic.Dictionary<int, UIGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<UIGroupConfig> _dataList;
    
    public TbUIGroupConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIGroupConfig>();
        _dataList = new System.Collections.Generic.List<UIGroupConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UIGroupConfig _v;
            _v = global::GameConfig.UIGroupConfig.DeserializeUIGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UIGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<UIGroupConfig> DataList => _dataList;

    public UIGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIGroupConfig Get(int key) => _dataMap[key];
    public UIGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

