
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbUIFormConfig
{
    private readonly System.Collections.Generic.Dictionary<int, UIFormConfig> _dataMap;
    private readonly System.Collections.Generic.List<UIFormConfig> _dataList;
    
    public TbUIFormConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIFormConfig>();
        _dataList = new System.Collections.Generic.List<UIFormConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UIFormConfig _v;
            _v = global::GameConfig.UIFormConfig.DeserializeUIFormConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UIFormConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<UIFormConfig> DataList => _dataList;

    public UIFormConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIFormConfig Get(int key) => _dataMap[key];
    public UIFormConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

