
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum UIFormId
    {
        /// <summary>
        /// 主菜单
        /// </summary>
        MainMenu = 0,
        /// <summary>
        /// 游戏界面
        /// </summary>
        GameHUD = 1,
    }

} 

