
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class UIGroupConfig : Luban.BeanBase
{
    public UIGroupConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Depth = _buf.ReadInt();
    }

    public static UIGroupConfig DeserializeUIGroupConfig(ByteBuf _buf)
    {
        return new UIGroupConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// UI 组名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// UI 组深度（CanvasLayer.Layer）
    /// </summary>
    public readonly int Depth;
   
    public const int __ID__ = -666942611;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "Depth:" + Depth + ","
        + "}";
    }
}

}

